set shell := ["powershell.exe", "-c"]

build:
    cargo build --target wasm32-wasip2


pack:
    just build
    cp ..\target\wasm32-wasip2\debug\slides_arrow.wasm .
    -rm ..\slides-lang\slides-modules\arrows.sld.mod.zip
    zip ..\slides-lang\slides-modules\arrows.sld.mod.zip slides_arrow.wasm
    -rm slides_arrow.wasm

setup:
    rustup target add wasm32-wasip2
