// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod component {
    pub mod arrows {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Type {
                Void,
                String,
                Int,
                Float,
            }
            impl ::core::fmt::Debug for Type {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Type::Void => f.debug_tuple("Type::Void").finish(),
                        Type::String => f.debug_tuple("Type::String").finish(),
                        Type::Int => f.debug_tuple("Type::Int").finish(),
                        Type::Float => f.debug_tuple("Type::Float").finish(),
                    }
                }
            }
            impl Type {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Type {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Type::Void,
                        1 => Type::String,
                        2 => Type::Int,
                        3 => Type::Float,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct Function {
                pub name: _rt::String,
                pub args: _rt::Vec<Type>,
                pub result_type: Type,
            }
            impl ::core::fmt::Debug for Function {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Function")
                        .field("name", &self.name)
                        .field("args", &self.args)
                        .field("result-type", &self.result_type)
                        .finish()
                }
            }
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod values {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub enum Value {
                Void,
                StringType(_rt::String),
                Int(i64),
                Float(f64),
            }
            impl ::core::fmt::Debug for Value {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Value::Void => f.debug_tuple("Value::Void").finish(),
                        Value::StringType(e) => {
                            f.debug_tuple("Value::StringType").field(e).finish()
                        }
                        Value::Int(e) => f.debug_tuple("Value::Int").field(e).finish(),
                        Value::Float(e) => {
                            f.debug_tuple("Value::Float").field(e).finish()
                        }
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod component {
        pub mod arrows {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod modules {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type Function = super::super::super::super::component::arrows::types::Function;
                pub type Value = super::super::super::super::component::arrows::values::Value;
                #[derive(Clone, Copy)]
                pub enum Error {
                    FunctionNotFound,
                }
                impl ::core::fmt::Debug for Error {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Error::FunctionNotFound => {
                                f.debug_tuple("Error::FunctionNotFound").finish()
                            }
                        }
                    }
                }
                impl ::core::fmt::Display for Error {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        write!(f, "{:?}", self)
                    }
                }
                impl std::error::Error for Error {}
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct Module {
                    handle: _rt::Resource<Module>,
                }
                type _ModuleRep<T> = Option<T>;
                impl Module {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `Module`.
                    pub fn new<T: GuestModule>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _ModuleRep<T> = Some(val);
                        let ptr: *mut _ModuleRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestModule>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestModule>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestModule>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _ModuleRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestModule>(&self) -> *mut _ModuleRep<T> {
                        Module::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`Module`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ModuleBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a Module>,
                }
                impl<'a> ModuleBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestModule>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _ModuleRep<T> {
                        Module::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for Module {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]component:arrows/modules"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-drop]module"]
                                fn drop(_: u32);
                            }
                            unsafe { drop(_handle) };
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_static_module_create_cabi<T: GuestModule>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::create();
                    (result0).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_module_available_functions_cabi<
                    T: GuestModule,
                >(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::available_functions(
                        unsafe { ModuleBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec5 = result0;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * (5 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5
                            .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                        {
                            let super::super::super::super::component::arrows::types::Function {
                                name: name2,
                                args: args2,
                                result_type: result_type2,
                            } = e;
                            let vec3 = (name2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = args2;
                            let len4 = vec4.len();
                            let layout4 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec4.len() * 1,
                                1,
                            );
                            let result4 = if layout4.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout4).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout4);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec4.into_iter().enumerate() {
                                let base = result4.add(i * 1);
                                {
                                    *base.add(0).cast::<u8>() = (e.clone() as i32) as u8;
                                }
                            }
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result4;
                            *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (result_type2.clone() as i32) as u8;
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1.add(0).cast::<*mut u8>() = result5;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_module_available_functions<
                    T: GuestModule,
                >(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base7 = l0;
                    let len7 = l1;
                    for i in 0..len7 {
                        let base = base7
                            .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base6 = l4;
                            let len6 = l5;
                            _rt::cabi_dealloc(base6, len6 * 1, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base7,
                        len7 * (5 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_module_call_function_cabi<T: GuestModule>(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let base8 = arg3;
                    let len8 = arg4;
                    let mut result8 = _rt::Vec::with_capacity(len8);
                    for i in 0..len8 {
                        let base = base8
                            .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                        let e8 = {
                            let l1 = i32::from(*base.add(0).cast::<u8>());
                            use super::super::super::super::component::arrows::values::Value as V7;
                            let v7 = match l1 {
                                0 => V7::Void,
                                1 => {
                                    let e7 = {
                                        let l2 = *base.add(8).cast::<*mut u8>();
                                        let l3 = *base
                                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len4 = l3;
                                        let bytes4 = _rt::Vec::from_raw_parts(
                                            l2.cast(),
                                            len4,
                                            len4,
                                        );
                                        _rt::string_lift(bytes4)
                                    };
                                    V7::StringType(e7)
                                }
                                2 => {
                                    let e7 = {
                                        let l5 = *base.add(8).cast::<i64>();
                                        l5
                                    };
                                    V7::Int(e7)
                                }
                                n => {
                                    debug_assert_eq!(n, 3, "invalid enum discriminant");
                                    let e7 = {
                                        let l6 = *base.add(8).cast::<f64>();
                                        l6
                                    };
                                    V7::Float(e7)
                                }
                            };
                            v7
                        };
                        result8.push(e8);
                    }
                    _rt::cabi_dealloc(
                        base8,
                        len8 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let result9 = T::call_function(
                        unsafe { ModuleBorrow::lift(arg0 as u32 as usize) }.get(),
                        _rt::string_lift(bytes0),
                        result8,
                    );
                    let ptr10 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result9 {
                        Ok(e) => {
                            *ptr10.add(0).cast::<u8>() = (0i32) as u8;
                            use super::super::super::super::component::arrows::values::Value as V12;
                            match e {
                                V12::Void => {
                                    *ptr10.add(8).cast::<u8>() = (0i32) as u8;
                                }
                                V12::StringType(e) => {
                                    *ptr10.add(8).cast::<u8>() = (1i32) as u8;
                                    let vec11 = (e.into_bytes()).into_boxed_slice();
                                    let ptr11 = vec11.as_ptr().cast::<u8>();
                                    let len11 = vec11.len();
                                    ::core::mem::forget(vec11);
                                    *ptr10
                                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len11;
                                    *ptr10.add(16).cast::<*mut u8>() = ptr11.cast_mut();
                                }
                                V12::Int(e) => {
                                    *ptr10.add(8).cast::<u8>() = (2i32) as u8;
                                    *ptr10.add(16).cast::<i64>() = _rt::as_i64(e);
                                }
                                V12::Float(e) => {
                                    *ptr10.add(8).cast::<u8>() = (3i32) as u8;
                                    *ptr10.add(16).cast::<f64>() = _rt::as_f64(e);
                                }
                            }
                        }
                        Err(e) => {
                            *ptr10.add(0).cast::<u8>() = (1i32) as u8;
                            match e {
                                Error::FunctionNotFound => {
                                    *ptr10.add(8).cast::<u8>() = (0i32) as u8;
                                }
                            }
                        }
                    };
                    ptr10
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_module_call_function<T: GuestModule>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = i32::from(*arg0.add(8).cast::<u8>());
                            match l1 {
                                0 => {}
                                1 => {
                                    let l2 = *arg0.add(16).cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                                2 => {}
                                _ => {}
                            }
                        }
                        _ => {}
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_hello_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::hello();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_hello<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                pub trait Guest {
                    type Module: GuestModule;
                    fn hello() -> _rt::String;
                }
                pub trait GuestModule: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]component:arrows/modules"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-new]module"]
                                fn new(_: *mut u8) -> u32;
                            }
                            unsafe { new(val) }
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]component:arrows/modules"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-rep]module"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn create() -> Module;
                    fn available_functions(&self) -> _rt::Vec<Function>;
                    fn call_function(
                        &self,
                        name: _rt::String,
                        args: _rt::Vec<Value>,
                    ) -> Result<Value, Error>;
                }
                #[doc(hidden)]
                macro_rules! __export_component_arrows_modules_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "component:arrows/modules#[static]module.create")] unsafe extern
                        "C" fn export_static_module_create() -> i32 { unsafe {
                        $($path_to_types)*:: _export_static_module_create_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Module > () } } #[unsafe
                        (export_name =
                        "component:arrows/modules#[method]module.available-functions")]
                        unsafe extern "C" fn
                        export_method_module_available_functions(arg0 : * mut u8,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_method_module_available_functions_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Module > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_component:arrows/modules#[method]module.available-functions")]
                        unsafe extern "C" fn
                        _post_return_method_module_available_functions(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*::
                        __post_return_method_module_available_functions::<<$ty as
                        $($path_to_types)*:: Guest >::Module > (arg0) } } #[unsafe
                        (export_name =
                        "component:arrows/modules#[method]module.call-function")] unsafe
                        extern "C" fn export_method_module_call_function(arg0 : * mut u8,
                        arg1 : * mut u8, arg2 : usize, arg3 : * mut u8, arg4 : usize,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_module_call_function_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Module > (arg0, arg1, arg2, arg3,
                        arg4) } } #[unsafe (export_name =
                        "cabi_post_component:arrows/modules#[method]module.call-function")]
                        unsafe extern "C" fn
                        _post_return_method_module_call_function(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_method_module_call_function::<<$ty as
                        $($path_to_types)*:: Guest >::Module > (arg0) } } #[unsafe
                        (export_name = "component:arrows/modules#hello")] unsafe extern
                        "C" fn export_hello() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_hello_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_component:arrows/modules#hello")] unsafe extern "C" fn
                        _post_return_hello(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_hello::<$ty > (arg0) } } const
                        _ : () = { #[doc(hidden)] #[unsafe (export_name =
                        "component:arrows/modules#[dtor]module")]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { unsafe { $($path_to_types)*:: Module::dtor::< <$ty as
                        $($path_to_types)*:: Guest >::Module > (rep) } } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_component_arrows_modules_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 16 + 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 16
                        + 2 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_host_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::component::arrows::modules::__export_component_arrows_modules_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::component::arrows::modules);
    };
}
#[doc(inline)]
pub(crate) use __export_host_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:arrows:host:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 678] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xab\x04\x01A\x02\x01\
A\x09\x01B\x05\x01m\x04\x04void\x06string\x03int\x05float\x04\0\x04type\x03\0\0\x01\
p\x01\x01r\x03\x04names\x04args\x02\x0bresult-type\x01\x04\0\x08function\x03\0\x03\
\x03\0\x16component:arrows/types\x05\0\x01B\x02\x01q\x04\x04void\0\0\x0bstring-t\
ype\x01s\0\x03int\x01x\0\x05float\x01u\0\x04\0\x05value\x03\0\0\x03\0\x17compone\
nt:arrows/values\x05\x01\x02\x03\0\0\x04type\x02\x03\0\0\x08function\x02\x03\0\x01\
\x05value\x01B\x16\x02\x03\x02\x01\x02\x04\0\x04type\x03\0\0\x02\x03\x02\x01\x03\
\x04\0\x08function\x03\0\x02\x02\x03\x02\x01\x04\x04\0\x05value\x03\0\x04\x01q\x01\
\x12function-not-found\0\0\x04\0\x05error\x03\0\x06\x04\0\x06module\x03\x01\x01i\
\x08\x01@\0\0\x09\x04\0\x15[static]module.create\x01\x0a\x01h\x08\x01p\x03\x01@\x01\
\x04self\x0b\0\x0c\x04\0\"[method]module.available-functions\x01\x0d\x01p\x05\x01\
j\x01\x05\x01\x07\x01@\x03\x04self\x0b\x04names\x04args\x0e\0\x0f\x04\0\x1c[meth\
od]module.call-function\x01\x10\x01@\0\0s\x04\0\x05hello\x01\x11\x04\0\x18compon\
ent:arrows/modules\x05\x05\x04\0\x15component:arrows/host\x04\0\x0b\x0a\x01\0\x04\
host\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\
\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
