[package]
name = "slides-rs-core"
version = "0.1.0"
edition = "2024"

[dependencies]
csscolorparser = "0.7.0"
enum_dispatch = "0.3.13"
markdown = "0.3.0"
strum = { version = "0.27.1", features = ["derive"] }
thiserror = "2.0.12"
